Resolve feature/game_core
YandexSpringfield/game pull request #10
Opened 2022-01-11 11:41 UTC by tigfamon

1. Добавлено два роута: для старта игры и для самой игры;
3. Добавлен базовый холст для старта игры. Отрисован главный персонаж, небо и земля;
4. Добавлен компонент `<Modal />` (модальное окно), которое будет использоваться в дальнейшем для завершения игры.
5. Добавлен класс `SpriteResolver` для работы со "спрайтами";
6. Добавлен класс `Core` для запуска игры.

2022-01-11 12:14 UTC, verobragina approved these changes

2022-01-11 12:14 UTC, verobragina commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +  // eslint-disable-next-line react/state-in-constructor
Думаю, можно вынести это в правило, если мы будем использовать такой синтаксис дальше

2022-01-11 12:14 UTC, verobragina commented on src/App.tsx
> +                <Route path={routes.game.start} element={<GameStart />} />
А есть ли смысл создавать отдельный роут для `GameStart`, если его раздача и так происходит по пути `/game`?

2022-01-11 12:21 UTC, pigarevaoks approved these changes

2022-01-11 12:21 UTC, pigarevaoks commented on src/components/ChangeAvatar/ChangeAvatar.tsx
> +      {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
я убрала это правило в .eslintrc, когда подмержишь мои изменения, эту строку можно не писать

2022-01-12 06:13 UTC, rnkupov requested changes

2022-01-12 06:13 UTC, rnkupov commented on src/components/Modal/Modal.tsx
> +  return createPortal(
return лишний 
проверку isOpen надо сделать до создания портала

2022-01-12 06:13 UTC, rnkupov commented on src/containers/GamePlay/Canvas/common.ts
> +export function loadImage(url: string): Promise<HTMLImageElement> {
стрелочная функция и без return

2022-01-12 06:13 UTC, rnkupov commented on src/containers/GamePlay/Canvas/core/Core.ts
> +/* eslint-disable no-plusplus */
убери, ++ усложняет код

2022-01-12 06:13 UTC, rnkupov commented on src/containers/GamePlay/Canvas/core/Core.ts
> +      groundRange.forEach(([x1, x2, y1, y2]) => {
надо бы переписать сложность получается n в кубе
и лучше вынести в отдельную функцию

2022-01-12 06:13 UTC, rnkupov commented on src/containers/GamePlay/Canvas/core/Core.ts
> +      skyRange.forEach(([x1, x2, y1, y2]) => {
надо бы переписать сложность получается n в кубе
и лучше вынести в отдельную функцию

2022-01-12 06:13 UTC, rnkupov commented on src/containers/GameStart/GameStart.tsx
> +  return (
return лишний

2022-01-12 19:32 UTC, merged