Feature/auth
YandexSpringfield/game pull request #3
Opened 2021-12-22 10:56 UTC by verobragina

Реализация разметки страниц авторизации и регистрации, добавлена валидация форм.

2021-12-22 15:00 UTC, tigfamon commented on src/components/Input/Input.tsx
> +      className={styles.input__field + (inputValid ? '' : ` ${styles.error}`)}
как идея, можем воспользоваться утилитой `classnames`, с ней легче и компактнее будет взаимодействовать с классами, которые зависят от пропсов.

2021-12-22 15:00 UTC, tigfamon commented on src/components/Input/types.ts
> +  errorMessage: string;
Можно два пропса объединить в один?
`error: string | boolean;`
В итоге если error не `undefined`, это означает, что инпут невалиден уже в любом случае. А если `typeof error === 'string'`, то можно показывать текст ошибки.

2021-12-22 15:00 UTC, tigfamon commented on src/components/Main-button/Main-button.tsx
> +  <input className={styles.button__main} type="submit" value={title} />
Получается, что мы не сможем использовать кнопку вне формы, так как она строго ограничена type="submit" ?
<br />
PS:
Чтобы не переписывать все пропсы от тега `button`, можно наследоваться от `DomAttributes<HTMLButtonElement>`. Вот пример:
```typescript
import {
  DOMAttributes,
  ButtonHTMLAttributes,
} from 'react';

export type BaseProps = {
  myProp: boolean,
};

export type Props = ButtonHTMLAttributes<HTMLButtonElement>
& DOMAttributes<HTMLButtonElement> & BaseProps;
```

2021-12-22 16:02 UTC, verobragina commented on src/components/Input/Input.tsx
> +      className={styles.input__field + (inputValid ? '' : ` ${styles.error}`)}
Поменяла

2021-12-22 16:03 UTC, verobragina commented on src/components/Input/types.ts
> +  errorMessage: string;
Да, так удобнее, спасибо

2021-12-22 17:00 UTC, pigarevaoks commented on src/components/Form/Form.tsx
> +  <form className={styles.form} action="" method="post" name={name}>
можно удалить  пустой`action=""`

2021-12-22 17:01 UTC, pigarevaoks commented on src/components/Input/Input.tsx
> +      {...rest}
лучше перенести `{...rest}` выше остальных свойств, чтобы их не перетереть

2021-12-22 17:02 UTC, pigarevaoks commented on src/pages/Registration/Registration.tsx
> +  onChange = (e) => {
можно типизировать `e`, например `onChange = (e:Event) => {`
и в остальных местах)

2021-12-22 17:36 UTC, rnkupov requested changes

2021-12-22 17:36 UTC, rnkupov commented on src/components/Input/Input.module.scss
> +  margin-bottom: 25px;
отступы относятся к сетке, лучше убрать у инпута

2021-12-22 17:36 UTC, rnkupov commented on src/components/Input/Input.tsx
> +      className={cn(styles.input__field, { [styles.error]: !!error })}
!!error 
лучше заменить на 
Boolean(error)
так нагляднее

2021-12-22 17:36 UTC, rnkupov commented on src/components/Input/types.ts
> +  error: string | boolean;
почему error с типом boolean? лучше использовать всегда строку, тогда не придется в компоненте инпута писать typeof error === 'string'

2021-12-22 17:36 UTC, rnkupov commented on src/components/Main-button/Main-button.tsx
> +  <input className={styles.button__main} type="submit" value={title} />
лучше переделать на тег button
type принимать в виде пропса

2021-12-22 17:36 UTC, rnkupov commented on src/components/Main-button/Main-button.module.scss
> +  margin: 10px 0;
у кнопки не должно быть внешних отступов

2021-12-22 17:36 UTC, rnkupov commented on src/components/Secondary-button/Secondary-button.module.scss
> +  margin: 10px 0;
это таже кнопка что и Main-button.tsx
объедини их и сделай модификатор в виде пропса
<Button view={'main' || 'secondary'}>
и в зависимости от него меняй стили

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Login/Login.tsx
> +export class Login extends Component<any, IState> {
нужно использовать функциональные компоненты

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Login/types.ts
> +    error: string | boolean;
только string

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Login/Login.module.scss
> +.container__login {
зачем position: absolute;?
используй гриды или флексы для выравнивания контента

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Registration/Registration.module.scss
> +  width: 550px;
используй гриды для выравнивания контента

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Login/Login.module.scss
> +  border: 0.5px solid #EAEAEF;
цвета везде в переменных а тут нет

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Login/Login.module.scss
> +  box-shadow: 0 1px 4px rgba(33, 33, 52, 0.1);
цвета везде в переменных а тут нет

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Registration/Registration.module.scss
> +  border: 0.5px solid #EAEAEF;
цвета везде в переменных а тут нет

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Registration/Registration.module.scss
> +  box-shadow: 0 1px 4px rgba(33, 33, 52, 0.1);
цвета везде в переменных а тут нет

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Login/Login.tsx
> +        error: false,
дефолтное состояние ошибки лучше сделать ''

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Registration/Registration.tsx
> +        error: false,
дефолтное состояние ошибки лучше сделать ''

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Registration/Registration.tsx
> +export class Registration extends Component<any, IState> {
тоже надо переписать на функциональный компонент

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Registration/Registration.tsx
> +    if (name !== 'password_confirm') {
лучше убрать инверсию в проверке

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Login/Login.tsx
> +  checkInput = (name: string, value: string) => {
в утилс

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Registration/Registration.tsx
> +  checkInput = (name: string, value: string) => {
в утилс

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Registration/Registration.tsx
> +  checkPasswords = (name: string, value: string) => {
в утилс

2021-12-22 17:36 UTC, rnkupov commented on src/pages/Registration/types.ts
> +    error: string | boolean;
только string

2021-12-22 17:38 UTC, tigfamon commented on src/components/Input/types.ts
> +  error: string | boolean;
а если понадобится просто подсветить инпут красным цветом, без отображения текста ошибки?

2021-12-22 17:39 UTC, rnkupov commented on src/components/Input/types.ts
> +  errorMessage: string;
лучше error: string

error ? <Error>{error}</Error> : null

Boolean('') === false

2021-12-23 12:40 UTC, tigfamon approved these changes

2021-12-23 12:43 UTC, pigarevaoks approved these changes

2021-12-24 05:59 UTC, rnkupov requested changes

2021-12-24 05:59 UTC, rnkupov commented on src/components/Button/types.ts
> +  view: string;
лучше на view написать enum

2021-12-24 05:59 UTC, rnkupov commented on src/pages/Login/Login.tsx
> +      default:
можно не писать

2021-12-24 05:59 UTC, rnkupov commented on src/pages/Login/Login.tsx
> +      default:
можно не писать

2021-12-24 05:59 UTC, rnkupov commented on src/pages/Login/Login.tsx
> +    switch (name) {
чтобы не писать большие switch можно сделать мапу
```
const nameToHandlerChange = {
    login: setLogin,
    password: setPassword,
}

nameToHandlerChange[name](value)
```

2021-12-24 05:59 UTC, rnkupov commented on src/pages/Registration/Registration.tsx
> +  const [firstName, setFirstName] = useState('');
а еще можно сделать стейт объектом

```
  const [fields, setFields] = useState({});

const onChange = (e) => {
    const { name, value } = e.target;
    setFields({ ...fields, [name]: value })
}
```

2021-12-24 05:59 UTC, rnkupov commented on src/pages/Registration/Registration.tsx
> +    const { value } = e.target;
деструкторизацию надо объединить

2021-12-24 08:32 UTC, rnkupov approved these changes

2021-12-24 08:32 UTC, rnkupov commented on src/pages/Login/Login.tsx
> +  const [fields, setFields] = useState({
в константу за пределами компонента
```
const initialFields = {
    login: '',
    password: '',
  }
```
сейчас объект дублируется и это плохо

2021-12-24 08:32 UTC, rnkupov commented on src/pages/Registration/Registration.tsx
> +  const [fields, setFields] = useState({
тоже что и в логине

2021-12-24 09:28 UTC, pigarevaoks approved these changes

2021-12-24 13:02 UTC, tigfamon approved these changes

2021-12-24 15:36 UTC, merged