Resolve feature/forum_page
YandexSpringfield/game pull request #4
Opened 2021-12-24 21:41 UTC by tigfamon

PR на инициализацию базового шаблона для внутренних страниц (Skeleton).

Набросал страницу форума, в детали элементов не погружался, т.к. пока неизвестно, что из себя будет представлять API. На странице примитивный рендер карточек с заголовком и контентом.

2021-12-24 22:08 UTC, verobragina approved these changes

2021-12-24 22:08 UTC, verobragina commented on src/containers/Header/styles.module.scss
> +    color: #4945FF;
У тебя есть переменная `$primary-color` или можно использовать цвет `$main-color`, который был на кнопке, чтобы было в одной цветовой гамме

2021-12-24 22:17 UTC, tigfamon commented on src/containers/Header/styles.module.scss
> +    color: #4945FF;
спасибо, подправил.
Заглянул в ui-kit на кнопках авторизации и регистрации цвет - `#4945FF`

2021-12-24 22:24 UTC, verobragina commented on src/containers/Header/styles.module.scss
> +    color: #4945FF;
Я заменила его на цвет из логотипа Mario - `#0B9BD7`

2021-12-27 13:25 UTC, pigarevaoks approved these changes

2021-12-28 16:27 UTC, rnkupov requested changes

2021-12-28 16:27 UTC, rnkupov commented on src/components/Avatar/Avatar.tsx
> +      <img className={styles.img} src={src} alt={alt || 'Avatar'} />
дефолтное значение перенеси в аргументы

2021-12-28 16:27 UTC, rnkupov commented on src/components/Avatar/Avatar.tsx
> +  return (
return тут лишний

2021-12-28 16:27 UTC, rnkupov commented on src/components/Card/Card.tsx
> +  return <div className={cn(styles.card, className)}>{children}</div>;
return тут лишний

2021-12-28 16:27 UTC, rnkupov commented on src/components/Content/Content.tsx
> +  return (
return тут лишний

2021-12-28 16:27 UTC, rnkupov commented on src/containers/Forum/index.tsx
> +  return (
return тут лишний

2021-12-28 16:27 UTC, rnkupov commented on src/containers/Forum/styles.module.scss
> +  &:not(:last-child) {
тут можно убрать not

2021-12-28 16:27 UTC, rnkupov commented on src/containers/Header/styles.module.scss
> +  &:not(:last-child) {
тут можно убрать not

2021-12-28 16:27 UTC, rnkupov commented on src/containers/Skeleton/Skeleton.tsx
> +  return (
return тут лишний

2021-12-28 17:27 UTC, tigfamon commented on src/containers/Forum/styles.module.scss
> +  &:not(:last-child) {
зачем убирать?

2021-12-28 17:27 UTC, tigfamon commented on src/containers/Header/styles.module.scss
> +  &:not(:last-child) {
зачем убирать?

2021-12-28 17:28 UTC, tigfamon commented on src/containers/Header/styles.module.scss
> +  &:not(:last-child) {
Мне нужно добавить отступ всем элементам, кроме последнего? Как сделать это без `&:not` ?

2021-12-28 18:41 UTC, rnkupov commented on src/containers/Header/styles.module.scss
> +  &:not(:last-child) {
```
.class {
  margin-right: 25px;

  :last-child {
    margin-right: 0;
  }
}
```

так читается легче

2021-12-28 18:45 UTC, tigfamon commented on src/containers/Header/styles.module.scss
> +  &:not(:last-child) {
![Снимок экрана 2021-12-28 в 21 44 10](https://user-images.githubusercontent.com/67568515/147597194-894a5526-bd2c-4bba-b5c2-67ebca62618d.png)

Изменил, но честно говоря, кроме того, что "читается легче" никакого профита не вижу.

2021-12-29 11:46 UTC, merged