Resolve feature/authAPI
YandexSpringfield/game pull request #5
Opened 2021-12-25 22:17 UTC by verobragina

Добавлено API авторизации и регистрации - запросы HTTP осуществляются через `axios`, полученные данные пользователя сохраняются в `store`.

2021-12-27 13:30 UTC, pigarevaoks approved these changes

2021-12-27 13:30 UTC, pigarevaoks commented on src/api/auth/auth.ts
> +      .then((res) => res)
можно `.then((res) => res)` не писать, при успехе, оно так и зарезолвится

2021-12-27 13:30 UTC, pigarevaoks commented on src/types/index.ts
> +export enum AuthError {
кажется, что это не подходит по енам, можно вынести в константу?
ниже тоже

2021-12-27 14:23 UTC, verobragina commented on src/api/auth/auth.ts
> +      .then((res) => res)
Исправила

2021-12-27 14:23 UTC, verobragina commented on src/types/index.ts
> +export enum AuthError {
Перенесла в `appConstants`

2021-12-27 17:08 UTC, tigfamon approved these changes

2021-12-28 16:35 UTC, rnkupov requested changes

2021-12-28 16:35 UTC, rnkupov commented on src/api/auth/auth.ts
> +    return await instanceAxios.post(PATH_API.AUTH.SIGN_UP, data);
return тут лишний

2021-12-28 16:35 UTC, rnkupov commented on src/api/auth/auth.ts
> +    return await instanceAxios.post(PATH_API.AUTH.SIGN_IN, data);
return тут лишний

2021-12-28 16:35 UTC, rnkupov commented on src/api/auth/auth.ts
> +    return await instanceAxios.get(PATH_API.AUTH.USER)
return тут лишний

2021-12-28 16:35 UTC, rnkupov commented on src/api/auth/auth.ts
> +    return await instanceAxios.post(PATH_API.AUTH.LOGOUT);
return тут лишний

2021-12-28 16:35 UTC, rnkupov commented on src/appConstants/index.ts
> +export {authError, registrationError} from '@appConstants/authErrors';
пробелы

2021-12-28 16:35 UTC, rnkupov commented on src/pages/Login/Login.tsx
> +          {Boolean(errorAuth) && <Error title={errorAuth} />}
Boolean можно убрать

2021-12-28 16:35 UTC, rnkupov commented on src/store/user/thunks/fetchUserProfile.ts
> +    return await authAPI
return лишний

2021-12-28 16:35 UTC, rnkupov commented on src/utils/utils.ts
> +  const result = {};
кажется что проще сделать так
```
let result = {...obj}
delete result[omitKey]
return result
```

2021-12-28 20:27 UTC, verobragina commented on src/store/user/thunks/fetchUserProfile.ts
> +    return await authAPI
Если я убираю return, у меня промис возвращается в таком виде:
![image](https://user-images.githubusercontent.com/58176309/147604165-2ebc8bc9-da94-424d-9cd7-66b943bb6b0e.png)

2021-12-29 07:44 UTC, rnkupov commented on src/store/user/thunks/fetchUserProfile.ts
> +    return await authAPI
ок, тут оставь

2021-12-29 13:18 UTC, merged