Resolve feature/errorBoundary
YandexSpringfield/game pull request #6
Opened 2021-12-27 13:31 UTC by pigarevaoks

2021-12-27 15:01 UTC, verobragina approved these changes

2021-12-27 15:01 UTC, verobragina commented on src/components/ErrorBoundary/types.ts
> +export type IProps = {
Лучше написать через префикс `T`, если ты используешь `type`. Ниже то же самое

2021-12-27 15:01 UTC, verobragina commented on src/components/ErrorBoundary/ErrorBoundary.module.scss
> +    align-items: center;
Есть `@mixin flex` для короткой записи

2021-12-27 17:12 UTC, tigfamon approved these changes

2021-12-27 17:12 UTC, tigfamon commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +          <span className={styles.errorBoundary__title}>
@verobragina , @pigarevaoks 

В css-модулях (а у нас они подключены) вовсе необязательно писать через синтаксис БЭМ.

Например, в этом случае просто `className={styles..title}` будет достаточно.

При сборке webpack добавит этому классу уникальный хэш, который основывается в том числе и на название директории. Таким образом, вероятность конфликта стилей сводится к нулю.
https://github.com/YandexSpringfield/game/blob/main/webpack.config.js#L49

2021-12-27 17:17 UTC, verobragina commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +          <span className={styles.errorBoundary__title}>
@tigfamon, ок

2021-12-28 10:38 UTC, pigarevaoks commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +          <span className={styles.errorBoundary__title}>
поправила

2021-12-28 10:38 UTC, pigarevaoks commented on src/components/ErrorBoundary/ErrorBoundary.module.scss
> +    align-items: center;
поправила

2021-12-28 10:38 UTC, pigarevaoks commented on src/components/ErrorBoundary/types.ts
> +export type IProps = {
поправила

2021-12-28 16:37 UTC, rnkupov requested changes
надо еще все приложение обернуть в ErrorBoundary

2021-12-30 07:18 UTC, rnkupov approved these changes

2021-12-30 07:54 UTC, merged