feature/profile
YandexSpringfield/game pull request #7
Opened 2021-12-29 15:42 UTC by pigarevaoks

2021-12-29 17:25 UTC, verobragina commented on src/components/ChangeAvatar/ChangeAvatar.tsx
> +import cn from 'classnames';
У тебя не используется этот импорт в файле

2021-12-29 17:25 UTC, verobragina commented on src/pages/Profile/Profile.tsx
> +  new_password_confirm: '',
Здесь лучше поля назвать, как у нас в API указано, если потом они будут передаваться на бэк:
![image](https://user-images.githubusercontent.com/58176309/147687790-a5759460-fdf9-430e-b262-4da7d0a104e0.png)

2021-12-29 23:29 UTC, tigfamon requested changes

2021-12-29 23:29 UTC, tigfamon commented on src/components/Input/types.ts
>    onBlur?: FocusEventHandler<HTMLInputElement>;
Чтобы не переписывать всевозможные события, можно также дополнительно наследоваться от `DomAttributes<HTMLInputElement>`.

2021-12-29 23:29 UTC, tigfamon commented on src/components/Input/types.ts
>    onBlur?: FocusEventHandler<HTMLInputElement>;
`DomAttributes` кстати говоря имортирован, но не используется. Проверь пожалуйста, что в IDE включен `eslint` и запусти вот [этот](https://github.com/YandexSpringfield/game/blob/main/package.json#L12) скрипт. Странно, что husky ни слова не сказал в момент коммита, что в файле есть неиспользуемые переменные.

2021-12-29 23:29 UTC, tigfamon commented on src/components/Input/types.ts
>    onBlur?: FocusEventHandler<HTMLInputElement>;
<img width="631" alt="Снимок экрана 2021-12-30 в 02 27 30" src="https://user-images.githubusercontent.com/67568515/147710395-1659bd24-f036-4632-a9ea-d66db21945cc.png">

А вот собственно профит того, что ты будешь использовать `DomAttributes`

2021-12-30 07:22 UTC, rnkupov approved these changes

2021-12-30 07:22 UTC, rnkupov commented on src/components/ChangeAvatar/ChangeAvatar.module.scss
> +	@include flex(column, flex-start,flex-start);
отступы

2021-12-30 07:22 UTC, rnkupov commented on src/pages/Profile/Profile.module.scss
> +  padding: 25px 30px;
отступы

2021-12-30 12:06 UTC, pigarevaoks commented on src/components/ChangeAvatar/ChangeAvatar.tsx
> +import cn from 'classnames';
поправила

2021-12-30 12:06 UTC, pigarevaoks commented on src/pages/Profile/Profile.tsx
> +  new_password_confirm: '',
поправила

2021-12-30 12:06 UTC, pigarevaoks commented on src/components/Input/types.ts
>    onBlur?: FocusEventHandler<HTMLInputElement>;
поправила

2021-12-30 12:07 UTC, pigarevaoks commented on src/components/ChangeAvatar/ChangeAvatar.module.scss
> +	@include flex(column, flex-start,flex-start);
поправила

2021-12-30 12:07 UTC, pigarevaoks commented on src/pages/Profile/Profile.module.scss
> +  padding: 25px 30px;
поправила

2021-12-30 12:12 UTC, tigfamon approved these changes

2021-12-30 12:14 UTC, verobragina approved these changes

2021-12-30 12:16 UTC, merged