feature/editProfile
YandexSpringfield/game pull request #9
Opened 2022-01-10 15:29 UTC by pigarevaoks

2022-01-10 16:06 UTC, tigfamon commented on src/components/Form/Form.tsx
> +  <form className={styles.form} method={method} name={name}>
Даже не знаю насчет атрибута `method`. Есть ли в нем необходимость вообще вместе с `axios`. По идее тип запроса определяется через `axios`, когда ты описываешь методы в классе.

Ну и лучше форму отправлять через `onSubmit`, тогда как минимум будет возможность вызвать "сабмит" при нажатии на `Enter` и при клике на кнопку, если у нее есть `type="submit"`

2022-01-10 16:06 UTC, tigfamon commented on src/pages/Profile/Profile.tsx
> +  const onEditProfile = (e) => {
Ага, вот этот метод лучше вызывать при `onSubmit` тега `form`. И затипизировать его лишним не будет:
```typescript
import { FormEventHandler } from 'react';

  const handleSubmit: FormEventHandler<HTMLFormElement> = (e) => {
    e.preventDefault();
    /// your code
  };
```

2022-01-11 10:28 UTC, verobragina approved these changes

2022-01-11 12:39 UTC, verobragina commented on src/pages/Login/Login.tsx
>      authAPI
Без `e.preventDefault()` теперь не работает авторизация
![image](https://user-images.githubusercontent.com/58176309/148943952-ba7ed766-dab2-4934-9acd-ae0335492bb4.png)

2022-01-11 13:28 UTC, pigarevaoks commented on src/pages/Login/Login.tsx
>      authAPI
ого, сейчас проверю и поправлю

2022-01-12 05:59 UTC, rnkupov requested changes

2022-01-12 05:59 UTC, rnkupov commented on src/pages/Profile/Profile.tsx
> +            onClick={onEditProfile}
событие onSubmit вешается на форму

2022-01-12 05:59 UTC, rnkupov commented on src/pages/Profile/Profile.tsx
> +            onClick={onEditPassword}
событие onSubmit вешается на форму

2022-01-12 05:59 UTC, rnkupov commented on src/pages/Profile/Profile.tsx
> +    const data = {
зачем создавать новый объект
если из fields надо удалить лишнее то это можно сделать так
```
const { password, ...data } = fields
```

2022-01-12 10:05 UTC, rnkupov approved these changes

2022-01-12 16:22 UTC, tigfamon approved these changes

2022-01-13 07:49 UTC, merged